In [1]:
#Import File
import pandas as pd
file_path = r'C:\Users\flori\Downloads\marketing_customer_analysis_clean.csv'

df_marketing = pd.read_csv(file_path)

# 1. X Y Split

In [2]:
# 1.X-y split (y is the target variable, in this case, "total claim amount")
df_marketing.total_claim_amount.unique()


array([292.8     , 744.924331, 480.      , ..., 273.018929, 381.306996,
       618.288849])

In [3]:
# Drop Null Values
df_marketing.dropna()

unnamed:_0 customer       state  customer_lifetime_value response  \
0               0  DK49336     Arizona              4809.216960       No   
1               1  KX64629  California              2228.525238       No   
2               2  LZ68649  Washington             14947.917300       No   
3               3  XL78013      Oregon             22332.439460      Yes   
4               4  QA50777      Oregon              9025.067525       No   
...           ...      ...         ...                      ...      ...   
10905       10905  FE99816      Nevada             15563.369440       No   
10906       10906  KX53892      Oregon              5259.444853       No   
10907       10907  TL39050     Arizona             23893.304100       No   
10908       10908  WA60547  California             11971.977650       No   
10909       10909  IV32877  California              6857.519928       No   

       coverage education effective_to_date employmentstatus gender  ...  \
0         Basic   College        2011-02-18         Employed      M  ...   
1         Basic   College        2011-01-18       Unemployed      F  ...   
2         Basic  Bachelor        2011-02-10         Employed      M  ...   
3      Extended   College        2011-01-11         Employed      M  ...   
4       Premium  Bachelor        2011-01-17    Medical Leave      F  ...   
...         ...       ...               ...              ...    ...  ...   
10905   Premium  Bachelor        2011-01-19       Unemployed      F  ...   
10906     Basic   College        2011-01-06         Employed      F  ...   
10907  Extended  Bachelor        2011-02-06         Employed      F  ...   
10908   Premium   College        2011-02-13         Employed      F  ...   
10909     Basic  Bachelor        2011-01-08       Unemployed      M  ...   

       number_of_policies     policy_type        policy  renew_offer_type  \
0                       9  Corporate Auto  Corporate L3            Offer3   
1                       1   Personal Auto   Personal L3            Offer4   
2                       2   Personal Auto   Personal L3            Offer3   
3                       2  Corporate Auto  Corporate L3            Offer2   
4                       7   Personal Auto   Personal L2            Offer1   
...                   ...             ...           ...               ...   
10905                   7   Personal Auto   Personal L1            Offer3   
10906                   6   Personal Auto   Personal L3            Offer2   
10907                   2  Corporate Auto  Corporate L3            Offer1   
10908                   6   Personal Auto   Personal L1            Offer1   
10909                   3   Personal Auto   Personal L1            Offer4   

       sales_channel  total_claim_amount  vehicle_class  vehicle_size  \
0              Agent          292.800000  Four-Door Car       Medsize   
1        Call Center          744.924331  Four-Door Car       Medsize   
2        Call Center          480.000000            SUV       Medsize   
3             Branch          484.013411  Four-Door Car       Medsize   
4             Branch          707.925645  Four-Door Car       Medsize   
...              ...                 ...            ...           ...   
10905            Web         1214.400000     Luxury Car       Medsize   
10906         Branch          273.018929  Four-Door Car       Medsize   
10907            Web          381.306996     Luxury SUV       Medsize   
10908         Branch          618.288849            SUV       Medsize   
10909            Web         1021.719397            SUV       Medsize   

      vehicle_type month  
0                A     2  
1                A     1  
2                A     2  
3                A     1  
4                A     1  
...            ...   ...  
10905            A     1  
10906            A     1  
10907            A     2  
10908            A     2  
10909            A     1  

[10910 rows x 27 columns]

In [4]:
df_marketing = df_marketing.drop_duplicates()

In [7]:
df_marketing.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='object')

In [12]:
#find numerical columns
numericals_df = df_marketing.select_dtypes(include ='number')
numericals_df.columns

Index(['unnamed:_0', 'customer_lifetime_value', 'income',
       'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'total_claim_amount', 'month'],
      dtype='object')

In [13]:
# X-Y Split
X = df_marketing[['customer_lifetime_value', 'income',
       'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'total_claim_amount', 'month']]
y = df_marketing ["total_claim_amount"]

# 2. Train-Test Split

In [14]:
# Train-test split
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 42)

# 3. Standardize the data

In [20]:
#MixMaxScaler
from sklearn.preprocessing import MinMaxScaler

In [25]:
X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

array([[0.24954704, 0.37560136, 0.53164557, ..., 0.125     , 0.31021685,
        1.        ],
       [0.07813874, 0.33327332, 0.18565401, ..., 0.25      , 0.17417093,
        0.        ],
       [0.00456644, 0.        , 0.02953586, ..., 0.        , 0.18731128,
        1.        ],
       ...,
       [0.07310297, 0.        , 0.03375527, ..., 0.125     , 0.11444345,
        1.        ],
       [0.03777879, 0.        , 0.03797468, ..., 0.25      , 0.11610254,
        1.        ],
       [0.44404234, 0.        , 0.2278481 , ..., 0.125     , 0.19076189,
        1.        ]])

In [36]:
scaler.transform(X_test)

array([[0.04783588, 0.95751193, 0.0464135 , ..., 0.25      , 0.16429372,
        1.        ],
       [0.01202724, 0.32813235, 0.05063291, ..., 0.        , 0.12107983,
        0.        ],
       [0.0032382 , 0.        , 0.02531646, ..., 0.        , 0.16670499,
        1.        ],
       ...,
       [0.01650036, 0.8921295 , 0.08438819, ..., 0.        , 0.01420035,
        0.        ],
       [0.07625516, 0.        , 0.06329114, ..., 0.125     , 0.12605712,
        0.        ],
       [0.03994245, 0.65641472, 0.01265823, ..., 0.25      , 0.03087038,
        0.        ]])

# 4. Apply linear regression

In [28]:
# Model Training
from sklearn.linear_model import LinearRegression

In [32]:
lm = LinearRegression()
model = lm.fit(X_train_scaled,y_train)

In [39]:
model.coef_
# Coefficients for all columns

array([ 1.91555384e-13, -5.52648350e-13,  2.70425202e-12,  8.82263185e-14,
       -8.03463015e-13,  2.53093980e-13,  4.73646059e-13,  2.89314067e+03,
       -1.24195494e-13])

In [40]:
model.intercept_
# Intercept 

0.09900700000099505

# 5. Model Interpretation

In [41]:
#Model Interpretation
random_row = X_test.sample()

In [42]:
model.predict(random_row)

C:\Users\flori\anaconda4\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([986816.46270385])

In [43]:
y_pred = model.predict(X_test)  #gives an array
y_pred = pd.DataFrame(y_pred)  # transform array into DF

C:\Users\flori\anaconda4\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [44]:
y_test = y_test.reset_index(drop=True)

In [48]:
residuals_df = pd.concat([y_test, y_pred],axis=1)

In [49]:
residuals_df

total_claim_amount             0
0             475.423848  1.375468e+06
1             350.400000  1.013757e+06
2             482.400000  1.395651e+06
3             673.342650  1.948075e+06
4             302.400000  8.748858e+05
...                  ...           ...
2723          460.266881  1.331617e+06
2724          405.883346  1.174278e+06
2725           41.182611  1.191472e+05
2726          364.800000  1.055418e+06
2727           89.411365  2.586798e+05

[2728 rows x 2 columns]

In [50]:
residuals_df = residuals_df.rename(columns={'total_claim_amount':'y_test',0:'y_pred'})

In [51]:
residuals_df["residual"] = residuals_df['y_test'] - residuals_df["y_pred"]

In [52]:
residuals_df.columns

Index(['y_test', 'y_pred', 'residual'], dtype='object')

In [53]:
residuals_df.head()

y_test        y_pred      residual
0  475.423848  1.375468e+06 -1.374993e+06
1  350.400000  1.013757e+06 -1.013406e+06
2  482.400000  1.395651e+06 -1.395169e+06
3  673.342650  1.948075e+06 -1.947402e+06
4  302.400000  8.748858e+05 -8.745834e+05

In [56]:
mean_error = residuals_df['residual'].mean()
mean_error

-1260187.0540618242

In [57]:
from sklearn.metrics import mean_squared_error as mse, mean_absolute_error as mae

In [58]:
mse(y_test,y_pred)

2283246428031.8936

In [59]:
mae(y_test, y_pred)

1260187.0540618242

In [61]:
import numpy as np
np.sqrt(mse(y_test,y_pred))

1511041.504404129